create database myproject;
use myproject;
CREATE USER 'pythonuser'@'localhost' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON myproject.* TO 'pythonuser'@'localhost';
FLUSH PRIVILEGES;
select*from mytable limit 5;
-- what is the total revenue generated by male vs female customers?
select gender , sum(purchase_amount) as revenue
from mytable group by gender 
-- which customers used the discount but still spent more than average amount?
select customer_id , purchase_amount
from mytable
where discount_applied = 'Yes'
and purchase_amount >= (select avg(purchase_amount) from mytable) 

-- Which are the top 5 products with the highest average review rating
select item_purchased, avg(review_rating) as "Average Product Rating"
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5 ;

-- Compare the average purchase amount between standard and express shipping
select shipping_type,
AVG(purchase_amount)
from mytable
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Do subscribers spend more?? Compare average spend and total revenue between subscribers and non subscribers.
select subscription_status,
COUNT(customer_id) as total_customers ,
avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue
from mytable
group by subscription_status
order by total_revenue,avg_spend desc;

-- Which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
round(
sum(case when 
discount_applied = 'Yes' then 1 else 0 end)* 100/ count(*),2) as discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;
-- segment customers into new ,returning , loyal based on their total number of previous purchases, and show the count of each segment
WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM mytable
)

SELECT
    customer_segment,
    COUNT(*) AS Number_Of_Customers
FROM customer_type
GROUP BY customer_segment;

-- What are the top 3 most purchased products within each category
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM mytable
    GROUP BY category, item_purchased
)

SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;

-- Are customers who are repeat buyers (more than 5 purchases ) also likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from mytable
where previous_purchases > 5
group by subscription_status

-- What is the revenue contribution of each age group
SELECT
CASE
    WHEN age BETWEEN 18 AND 25 THEN '18-25'
    WHEN age BETWEEN 26 AND 35 THEN '26-35'
    WHEN age BETWEEN 36 AND 45 THEN '36-45'
    ELSE '46+'
END AS age_group,
SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Which category generates the highest revenue in each season?
SELECT
    season,
    category,
    SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY season, category
ORDER BY season, total_revenue DESC;

-- Which payment method is preferred for high-value purchases (>$100)?
SELECT
    payment_method,
    COUNT(*) AS high_value_orders,
    SUM(purchase_amount) AS revenue
FROM mytable
WHERE purchase_amount > 70
GROUP BY payment_method
ORDER BY revenue DESC;

-- Which location contributes the highest revenue?
SELECT
    location,
    SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 10;

-- Which customers spend above the average of their gender?
SELECT
    customer_id,
    gender,
    purchase_amount
FROM mytable m1
WHERE purchase_amount >
(
SELECT AVG(purchase_amount)
FROM mytable m2
WHERE m1.gender = m2.gender
);

-- Which product category has the highest percentage of subscribers?
SELECT
    category,
    ROUND(
    SUM(CASE WHEN subscription_status='Yes' THEN 1 ELSE 0 END)
    *100/COUNT(*),2) AS subscriber_percentage
FROM mytable
GROUP BY category
ORDER BY subscriber_percentage DESC;

-- Which size generates the highest revenue?
SELECT
    size,
    SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY size
ORDER BY total_revenue DESC;

-- Find the top spending customer in every location.
WITH customer_sales AS
(
SELECT
location,
customer_id,
SUM(purchase_amount) AS total_spent,
RANK() OVER(PARTITION BY location ORDER BY SUM(purchase_amount) DESC) rnk
FROM mytable
GROUP BY location,customer_id
)

SELECT *
FROM customer_sales
WHERE rnk=1;

-- Which category has the highest repeat purchase rate?
SELECT
category,
ROUND(
SUM(CASE WHEN previous_purchases>1 THEN 1 ELSE 0 END)
*100/COUNT(*),2) AS repeat_rate
FROM mytable
GROUP BY category
ORDER BY repeat_rate DESC;

-- Compare average ratings between subscribers and non-subscribers.
SELECT
subscription_status,
ROUND(AVG(review_rating),2) AS avg_rating
FROM mytable
GROUP BY subscription_status;

-- Which shipping type generates the highest revenue after discounts?
SELECT
shipping_type,
SUM(purchase_amount) AS revenue
FROM mytable
WHERE discount_applied='Yes'
GROUP BY shipping_type
ORDER BY revenue DESC;